name: Docker Image

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Docker Image
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make dockerimage
        make dockerpush
