name: Docker Image

on:
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Set up Go 1.13
      uses: actions/setup-go@v1.1.2
      with:
        go-version: '1.13.x'
    - name: Generate client
      run: make generate-client
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Test
      run: make test
    - name: Build and Push Docker Image
      run: |
        docker login -u metalstackci -p ${{ secrets.DOCKER_HUB_TOKEN }}
        make dockerimage
        make dockerpush
