name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Extract branch name
      shell: bash
      run: echo "::set-env name=RELEASE_TAG::$(echo ${GITHUB_REF##*/})"
    - name: Docker Image
      uses: metal-stack/action-docker-make@master
      with:
        username: metalstackci
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        args: "--no-lint -b release"
